### ISSUE TITLE
testing with WFT 

### ISSUE THREAD

**Issue by SeonYoo-Kim** [TArdelean/AnomalyLocalizationFCA#2]
When testing with the WFT dataset, why does it not output image-level auroc?

**Comment by TArdelean** [comment]
In the WFT dataset all test images contain anomalies, therefore predicting 'anomaly' for all images will yield a perfect image-level auroc, making it meaningless in this case.

**Comment by SeonYoo-Kim** [comment]
Thank you so much for sharing your comment!!
